### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by montogeek** [twostairs/paperwork#104]
Is there any plans to add keyboard shortcuts?

**Comment by devilx** [comment]
Good idea! What kind of shortcuts would you expect to see in Paperwork?

**Comment by Baldrs** [comment]
I'd would expect a setting to disable them alongside with them. For example, they will definitely will conflict with chrome extensions that provide vim emulation.

**Comment by jasondavis** [comment]
Please add keyboard shortcuts to at least do these...

- `CTRL+S` - Save
- `CTRL+N` - New Note

I find myself constantly trying to hit `CTRL+S` to save the records!

**Comment by swengmatt** [comment]
I would like to try to take this on, maybe use a library like [AngularHotkeys.js](http://chieffancypants.github.io/angular-hotkeys/)

**Comment by devilx** [comment]
:+1:

**Comment by jasondavis** [comment]
I would like to expand on it with some nice libraries that I have seen other projects use to add keyboard shortcuts support...

When I say keyboard shortcuts I mean something similar to this...
- `CTRL + S` - Save Note  
- `CTRL + N` - Create new note



## 1) KeyCSS - CSS Library to show nice looking Keyboard Keys
This CSS library is useful for providing a nice screen to show the available keyboard shortcuts. 
http://michaelhue.com/keyscss/

You can see a demo in the attached image below of how it looks using this CSS library.
![4](https://cloud.githubusercontent.com/assets/186818/6056675/556f9a08-ace2-11e4-9afa-00ef1d0ee898.png)


## 2) Mousetrap - Lightweight JavaScript library for keyboard input detection
There are many great open source libraries for keyboard detection however I figured while on the subject I would post one of my favorites.  The reasons are is because it is really lightweight  and easy to use!  
It's called Mousetrap - http://craig.is/killing/mice

#### Example usage...

    // single keys
    Mousetrap.bind('4', function() { highlight(2); });
    Mousetrap.bind('x', function() { highlight(3); }, 'keyup');

    // combinations
    Mousetrap.bind('command+shift+k', function(e) {
        highlight([6, 7, 8, 9]);
        return false;
    });

    Mousetrap.bind(['command+k', 'ctrl+k'], function(e) {
        highlight([11, 12, 13, 14]);
        return false;
    });

    // gmail style sequences
    Mousetrap.bind('g i', function() { highlight(17); });
    Mousetrap.bind('* a', function() { highlight(18); });

    // konami code!
    Mousetrap.bind('up up down down left right left right b a enter', function() {
        highlight([21, 22, 23]);
    });

**Comment by swengmatt** [comment]
AngularHotkeys.js actually uses Mousetrap to do the key bindings.
The problem I did run into is 2-fold:

1. Things like Ctrl + N in Chrome opens up a new window.  I'm not even sure what would happen in other browsers; making customizable hotkeys would probably be the best answer, but I would like some feedback for that idea. 
2. Also, to be able to add a checkbox to be able to disable them altogether requires a bit more changes than I originally anticipated in POSTing the settings back to the server-side. But, I figure once this is done, maybe it would be easier to allow the user to make their own hotkey combinations, but then what would the defaults be if any?

**Comment by DavidWiesner** [comment]
@devilx I think the shortcuts used in [laverna-webapp](https://laverna.cc/app) are good to start a discussion. I removed some shortcuts they won´t make sense in paperwork.

|Action	|	Keybindings|
|-------|----------|
|Edit	|	e|
|Open	|	o|
|Save      | Ctrl+s |
|Remove	|	shift+3|
|Create new note	|	c|
|Keyboard help	|	?|
|Search note	|	/|
|Go to inbox	|	g i|
|Go to notebook list	|	g n|
|Go to removed notes	|	g t|
|Bottom	|	j|
|Top	|	k	|
