### ISSUE TITLE
Delete tags that are no longer available

### ISSUE THREAD

**Issue by nikhilben** [twostairs/paperwork#177]
If a tag is associated exclusively to a note, deleting that note also should delete that tag. Else they will be shown in "Tags" section, even though no notes are associated with it. Nothing happens on clicking these tags (as no notes are available). There should be some way to clean up these 'orphan' tags ?

**Comment by Liongold** [comment]
Is this for a 'Delete Tag' feature?

**Comment by nikhilben** [comment]
@Liongold Not really. 

 I think the most elegant way is to automatically delete the tag while deleting the note (only if the tag is not associated with some other note). 

May be use the Laravel model events ? Whenever a note is removed from the model, check if the tags associated with it is associated with some other notes. If not, delete those tags.  Thus the "Tags" section will only show actual tags, and will not be cluttered with nonexistent tags. 

I don't know if this is the best solution :)

**Comment by devilx** [comment]
@nikhilben thank you for the suggestion. Some thoughts on it though:

Deleting tags -> should be definitely available. Maybe through an additional menu entry on top and (soon) via a context menu (right click). But: Deleting a tag when the last note that uses it was deleted? If right now Evernote would do this to me (and many other users) I'd go pretty mad ad them. Example:

I use to collect every coffee roast I want to purchase sometime in the future within a notebook. For each of these, I have tags which define the coarse grind I'm planning to get. Now, only because I deleted the last coffee I wanted to get as a fine-grinded espresso roast, I don't want the actual tag to be deleted. I will use the tag again, as soon as I find another coffee I'd like to have with these settings.

I personally have a couple of more use cases, in which tags (even though they might be empty) might serve a purpose in the near future.

Another thing: Paperwork currently does not really delete notes. Instead, it uses soft-deletion, by setting the note's deleted_at timestamp within the database. Now, sometime in future, we might be able to provide "deleted note recovery" as a feature. At that point, a user would expect to be able to fully recovery a note with all its details (e.g. tags). When a tag was deleted by him manually (using some right-click context menu -> delete action), he probably won't expect the tag to re-appear on recovered notes. But when we delete a tag, only because the last visible (deleted_at === NULL) note is gone, user's might be wondering, where all their tags were gone, after recovering a previously deleted note.

**Comment by devilx** [comment]
I thought some more about this and think it's not a great idea to remove the user's tags. Not only, because we would end up in quite some trouble on the technical side of this enhancement, but also because I believe that users like to keep empty tags by default, which is why Evernote and all the others leave them until the user actively removes them manually.
