### ISSUE TITLE
Notebooks sharing with other Paperwork-users

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#18]
It should be possible to share notebooks with other Paperwork-users. Therefor, a dialog/page is needed, which lets the user invite someone else to a notebook and define his/her permissions.

**Comment by devilx** [comment]
Before the UI can be built, an API needs to be implemented -> #26.

**Comment by clemlaf** [comment]
I made a few steps in that direction in the branch [clemlaf/paperwork/add-share](https://github.com/clemlaf/paperwork/tree/add-share).
I implemented a "share Note" function and a "share Notebook" function on the API side (in the Note and Notebook controllers), and added a "share Note" entry in the Edit menu on the UI side. It shows a User selection modal screen in order to define the permission given each user (via a select field).
It is only work in progress but it answers to this issue.

**Comment by clemlaf** [comment]
This issue is partly solved by #386, isn't it ?
