### ISSUE TITLE
Can't create new note

### ISSUE THREAD

**Issue by Tagnard** [twostairs/paperwork#184]
I am using the latest version through fig and when i try to create a new note i get error 500 with the message. 

    SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content_preview' at row 1

**Comment by Baldrs** [comment]
Any additional text in message? Like file name or line? Any traces? At least URL of the requested resource?

**Comment by devilx** [comment]
Did you try to upload an image containing text? Maybe the tesseract OCR parsed an crazy amount of text out of it.

**Comment by Tagnard** [comment]
Here is the full message.
https://gist.github.com/Tagnard/fe83454714010b095e27

**Comment by devilx** [comment]
Ah. That explains it. The content_preview column should only save a preview of the note's content, in order to display it within the notes list. It looks like right now, it tries to save everything it receives as content, without cutting the content correctly at a maximum point.

I will fix this while working on issue-66-feature.

**Comment by narcolepticsnowman** [comment]
#295  pull request fixed this.
