### ISSUE TITLE
Adjust GIT workflow?

### ISSUE THREAD

**Issue by devilx** [twostairs/paperwork#186]
Just had a conversation with @joshlemer on [gitter](https://gitter.im/twostairs/paperwork) regarding this:

```
devilx 23 minutes ago 
Hey guys... I'm pretty stuck right. I'm working on the branch https://github.com/twostairs/paperwork/tree/issue-66-feature, unfortunately development goes on waaaay too slow. Now the thing is... you guys change a lot of structure within Paperwork – which I appreciate! – but unfortunately it makes it impossible for me to develop on this UUID change, as I end up with new conflicts every day.
Now.. here's the thing. A few weeks ago, while there were only @Liongold, @joshlemer and me, I would have just committed this broken feature to master and slowly refactor everything until the whole setup worked again. Since we seem t have quite a lot of people trying out Paperwork recently, I'm not sure whether that's still a good idea.
What do you guys think?
Right now I'm feeling a bit like Sisyphus, with all these great changes to Paperwork everyday. :smile:

joshlemer 15 minutes ago 
Is it a particular area of the codebase which changing causes conflicts with your branch?

devilx 12 minutes ago 
Since I need to work on the API as well as on the web client functionality, there are a lot of things that cause conflicts. ApiNotesController.php caused conflicts a few days ago, the restructuring of the paperwork.js stuff will cause conflicts later on. And it's pretty much every change to the API/middle-ware or the consuming parts that will keep breaking.

joshlemer 8 minutes ago 
What if there were an additional long lived branch called develop, which is not guaranteed stable? I'm on my phone right now but here's a git workflow that may be appropriate. The only thing that I'm not sure about is if you can set github pull request merges to have the --no-ff flag
http://nvie.com/posts/a-successful-git-branching-model/
```

For me, the workflow suggested by @joshlemer looks pretty good. What do you other guys think? Could we implement it here that way?

**Comment by swengmatt** [comment]
Thats pretty much how I setup my repos, and atlassian has a cool local git repo manager that supports that kind of workflow [sourcetree](http://www.sourcetreeapp.com/)

**Comment by joshlemer** [comment]
Ah hah, my initial worry about the ability to implement gitflow on github are no longer a concern, because [all pull requests merge with the --no-ff option](https://help.github.com/articles/merging-a-pull-request/), so we're already ready to go. We'll need to keep this in mind though when merging develop into master though. That is, merging develop into master should be done either with an actual pull request, or if done by @devilx, should be done with the --no-ff flag.

A quick google search turned up some [packages that abstract this workflow](https://github.com/nvie/gitflow), even [github specific ones](http://datasift.github.io/gitflow/GitFlowForGitHub.html), but in my opinion, using extensions like this would likely raise the barrier to entry for new contributors.  
  
With vanilla git/github, changes other contributors will have to take into account will include that if they want to start developing / contributing to Paperwork, they need to be pulling from / pull requesting to the develop branch, while users will want to get from the master branch obviously.

**Comment by joshlemer** [comment]
@Liongold @Baldrs I thought I'd mention you guys to chime in if you have any issues with this style of development.

**Comment by Baldrs** [comment]
No issues, lets add devel branch for intense merging and let @devilx decide when to merge into master and us to merge into devel all these intense changes we add and break things(As I have messed up with that comma)

**Comment by Baldrs** [comment]
And let's add the contributing guide somewhere where we all agree on how to contribute and on standards we use in code for all the stuff.

**Comment by devilx** [comment]
All open pull requests have been merged to the master now. I will now create the develop branch.

**Comment by devilx** [comment]
Should master be pulled into develop using a regular merge or by using rebase?

**Comment by joshlemer** [comment]
You could either just do a regular merge of master into develop (it's just a fast-forward) or you could just delete the develop branch and branch a new one from master

**Comment by Baldrs** [comment]
I vote for the second variant.

**Comment by devilx** [comment]
As I didn't perform anything so far, I was wondering that's the status of master and develop, as I've seen that new commits have been merged into master and develop as well...? @Baldrs @joshlemer

**Comment by Baldrs** [comment]
I haven't merged anything into master after we agreed on a new workflow, as I recall

**Comment by devilx** [comment]
Okay. We'll just move along, as there's nothing to see here. :-) let's close this for now then.
