### ISSUE TITLE
Sandstorm.io port

### ISSUE THREAD

**Issue by CoolkcaH** [twostairs/paperwork#199]
A port to Sandstorm.io would have many advantages. It's the future of web-apps.
A direct port is possible, but using the Sandstorm API would be much better and make the app easier to maintain and develop.

See this thread I started:
https://groups.google.com/forum/#!topic/sandstorm-dev/JXrDH8APlkU

Apps currently ported:
https://sandstorm.io/apps

**Comment by Baldrs** [comment]
It does not support php, I think? Why do we must port it to anything anyway? For one platform instead of billions running PHP? Or to nodejs while there are no reason? This is no-go.

**Comment by jasondavis** [comment]
I agree, personally I love the fact that it is built in my language of choice: PHP and further on my favorite framework Laravel!  My dream app on my favorite platform...perfect how it is in my opinion

**Comment by Baldrs** [comment]
It seems to support PHP but it changes the applications in some way, for example WordPress is not just run on that platform, it is changed in some way, and I, personally, don't like the way they changing things or losing cross-platform app to a single platform anyway. It may be good if someone will maintain and adapt Paperwork to work with that thing, but I see no reason to do this. If you need this, do it yourself, you are even welcome, as it is free and open source software.

**Comment by CoolkcaH** [comment]
Baldrs, this was meant as a suggestion to generate discussion. Marking as wontfix instead of enhancement is the kind of thing that can drive developers and users away. I am a dev and maybe would consider contributing to paperwork in the future. I am not affiliated with Sandstorm, but I'm interest because I want to start running web-apps on my own and want a good platform I trust.

If Paperwork is successful, it will be ported to Sandstorm. If the Paperwork devs want to collaborate it would be beneficial to both projects:

Sandstorm does support PHP, in fact making a PHP app work is very easy.
From the website, "Use any tech stack that runs on Linux — Node, Rails, PHP, Java, Python, whatever".
But the more functionality of the Sandstorm API is used, the more advantages it has.

For example, you get notes or notebooks sharing between users and between other apps for free, with no development effort required, because all that work is done for you by Sandstorm. Easy connectivity to other apps would also enable a lot more features without extra development work.

- Security is Built-in
You don't have to implement login. You don't even have to implement sharing — Sandstorm does that for you. You can even export APIs and integrate with other apps without thinking about OAuth. Sandstorm protects you and your users from most common security problems, so you can rest easy.

- For users, Sandstorm makes it very easy to install web-apps, will have an easy to use Web-app Store. They can pay for hosting or host in their server. For Paperwork, it's a good way to get donations from users because they will have a pay-what-you-want model if you wish to enable that.

- For users, trusting security is always a problem. As a developer myself I know how hard it is to implement good security and authentication. Sandstorm is also open-source and because it will support many apps, a lot more people will be working on core security. Also the Sandstorm devs are respected and have a lot of experience working on the technologies being used (main dev is an ex-Google he developed Protocol Buffers v2 (RPC used by Google) and the new Cap'n Proto used in Sandstorm, and Asheesh Laroia was a Security Engineer at Eventbrite.

- You can keep developing the standalone Paperwork, but if you make it modular, by separating the core functionality (notes) from the rest (login. security, sharing, etc.) your code will be better and easier to keep cross-platform. If you already do that, using Sandstorm or any other platform is even easier.

**Comment by Baldrs** [comment]
Ok, lets ask @devilx about his opinion on this. This is not enhancement, this is the change of lot of the things and much of development effort anyway.

**Comment by CoolkcaH** [comment]
A basic port doesn't seem difficult. Since you already support Docker in Paperwork, it seems to be even easier.
Of course to take advantage of all the features instead of just running as is would take more effort.

https://blog.sandstorm.io/news/2014-05-12-easy-port.html

https://github.com/sandstorm-io/sandstorm/wiki/Porting-Guide

https://groups.google.com/forum/#!searchin/sandstorm-dev/php/sandstorm-dev/fxFjqXUXht0/xRjHcWPKOtgJ

**Comment by jasondavis** [comment]
Another thing to consider is most of the apps that it supports are matured apps that aren't being developed in their infancy stage.  Perhaps if this were implemented if should be down the road, a year or more even.  Just my thoughts out loud.

**Comment by CoolkcaH** [comment]
jasondavis, 
It is possible now to run the whole Paperwork app without big modifications inside Sandstorm, just like it does now with Docker. Sandstorm supports the conversion of the Docker container. 
So that is a way to make it run easily and it would probably be the easiest way for a end user to install Paperwork, especially after Sandstorm opens the Indie App Store. 

Right now for end-users it's not so easy to install webapps, even with Docker, they would prefer not to use the command line at all. It will be one-click when hosted by Sandstorm, and very easy to self-host too, they will even automate the DNS service.

Using Sandstorm as a platform actually saves a lot of development effort because it supports security and authentication, and will support sharing between users and between apps (like open a note in an app that uses it for something else).

However Sandstorm is still in development, it will be a few months before it is ready for all that. 
The Powerbox for example that would allow for sharing of notes or notebooks is not ready yet.

After that, it's a choice about how many Sandstorms features the devs want to use, I think it will allow devs to focus on core functionality (notes/clips) and less effort in things that are common to all apps. Scalability would also be taken care of.

**Comment by Baldrs** [comment]
Rule of thumb in open-source - you need it, you do it.

**Comment by devilx** [comment]
@CoolkcaH thank you for suggesting this. Let me tell you my honest opinion about Sandstorm.io as it is today. 

Basically, I find it an interesting concept: Building an *app store* for the open-source world (or more precisely for open-source web services, just like Paperwork is one) – at least, if I should have gotten the idea right, because there is no clear statement about what problem Sandstorm actually tries to solve. Neither sandstorm.io nor the GitHub readme provides detailed insights on this topic. Browsing through the rest of its documentation showed me, that not only the "plot" is missing, but also important practical documentation. Judging the very sophisticated idea sandstorm seems to follow, documentation is the number one thing needed by projects (like us) in order to consider porting.

However, in search for more useful documentation about Sandstorm I stumbled across an interesting post in the [Sandstorm blog](https://blog.sandstorm.io/news/2014-08-19-why-not-run-docker-apps.html), which outlines a few points:

> Every app must have a web interface, and they must expose all configuration options through that interface.
>
> Users expect their data to be organized in units of documents or other semantic objects, not in units of databases or relational tables. Apps must set up their own database and encapsulate it appropriately; the user won’t do it for them.
>
> Users should not have to log into every app separately, especially when the app instance already belongs specifically to them and Sandstorm is already protecting access. So, apps must integrate with Sandstorm’s unified login system.
>
> It would also be nice if users did not have to master a different sharing model for every app. Sandstorm supports fine-grained containers, such that every document can actually be in a separate container. This way, the platform can handle sharing consistently across all apps, by applying sharing to the containers. But, apps have to be designed for this.
>
> Permission grants must be expressed in a way that users can understand. A user does not know what it means to allow an app to communicate on port 25, but they do know what it means to allow an app to send and receive e-mail under a particular e-mail address. In order for such permissions to be enforceable, the platform’s security model must actually operate in terms of these semantic permissions, not arbitrary TCP connections.
>
> Updating an app must be a one-click (or even automatic) process. This means there must be a clearly-defined separation between the app “image” and its instance data, so that the platform is able to replace the former without harming the latter.
>
> Users will install malicious apps from time to time, and they must be protected from these. The regular Linux kernel interface is far too wide, and critical exploits are found too often. We must instead present a much narrower interface and force apps to adapt. See our previous post on this.

These points clearly show, that Sandstorm is not designed for a wide variety of customers but rather one specific sort, that prefers comfort over (apparent) complexity. With Paperwork though, I (and probably a couple of more devs contributing to the project) want to allow a huge variety of people to use Paperwork, without taking control away from them. Not only people who want to run Paperwork on their own Linux machine at home, but also the guys that want to use it inside their embedded systems (e.g. NAS) or the admins that plan to introduce Paperwork in their enterprise should be able to set up and run the project.

At the current state of the Sandstorm project, I don't see how all these different persons would benefit from having this additional abstraction layer between them and Paperwork – not to mention that several of Sandstorm's philosophies just won't work in certain environments. Which corporate admin prefer some reinvented wheel in terms of single-sign-on (*Sandstorm’s unified login system*) when they could just integrate Paperwork (or whatever service) into their existing LDAP/Active Directory infrastructure? Which typical *Debian stable admin* would want to run a whole bunch of software, that wasn't packaged and provided through a (gpg signed) package management source, but instead installed by executing ```curl https://install.meteor.com/ | sh```, ```curl https://install.sandstorm.io | bash``` or whatever similar command? How could Paperwork be packaged for *.deb/*.rpm based systems, with a dependency like Sandstorm? How could it ever be built as a SynologyCommunity package?

Another good point concerns security. With an additional layer like Sandstorm in between, security becomes an even harder to manage topic. Especially, since Sandstorm's base is partially built using lower level languages like C and C++. These languages aren't known for being very fault-tolerant and mistakes in memory/buffer management can lead to serious security issues there. And the Sandstorm website really didn't take away the fear from me, since the ("Security" section)[https://sandstorm.io/#security] contains of nothing more than buzzwords and marketing *blabla*. It does not give any insight on **how** Sandstorm actually enhances security. Telling that developers are stupid and write bugs (quote: *most developers don't think enough about security, and they end up producing apps that have bugs allowing hackers to get in.*) doesn't make Sandstorm a secure platform. The only thing it does is insult "most developers".

Now, what about for example scalability? Or high-availability? How does Sandstorm allow implementing highly available or even scalable setups? I could go on like this for hours. There are just too many questions with (right now) too little or no answers at all.

To come to an end, this uncertainty is what keeps me from saying *"Yes, we're going to support Sandstorm!"*. In addition to all these technical thoughts, I'm also unsure whether I like the way Sandstorm.io wants to build a business for themselves. 

From what I understood, the hosted variant of Sandstorm.io will allow you to easily use all the open-source projects that were ported to Sandstorm on a pre-installed environment ran by Sanstorm, Inc. (or whatever the company is called). Basically, Sandstorm tries to convince open-source projects to invest time and work for adopting its specific structure and then generates profits by providing open-source projects as a service. And, due to the fact that it's licensed under the Apache License 2.0, Sandstorm could include features within their SaaS service, which are exclusive to them and won't be made open-source, attracting more users to their hosted environment. So, how do the actual open-source projects themselves benefit from the whole thing in the end? In my opinion, they don't benefit at all.

I will close this request for now. I'm not saying that Sandstorm won't ever be supported by Paperwork, but I would want to wait and see, how Sandstorm evolves. Time will tell, whether it'll be the "next big thing" in open-source hosting and – what's more important for us – whether for example Laravel would jump the Sandstorm-train by providing a native integration to it. This is probably the first step that Sandstorm-evangelists should work on anyway.

**Comment by kentonv** [comment]
Hi! I'm the founder and lead developer of Sandstorm. Just want to clarify a few points:

> With Paperwork though, I (and probably a couple of more devs contributing to the project) want to allow a huge variety of people to use Paperwork, without taking control away from them.

I don't think @CoolkcaH is suggesting that Paperwork should _require_ Sandstorm, just support it. That is, the core would remain independent of Sandstorm, but there would be a Sandstorm package built as one option for deployment, which means the user would have more choices, not fewer.

That said, it is of course up to you whether you think this is worthwhile.

> It does not give any insight on how Sandstorm actually enhances security.

Yes, we need to add some links there to better explanations. The problem is, it's hard to summarize how we improve security because practically everything we do is in some way intended to improve security. :)

Some of our security measures include:
- We handle login at the platform level so that apps never handle user credentials -- which means they can't leak those credentials.
- We handle access control at the platform level so that an app can never accidentally grant access to someone who shouldn't have it.
- We serve apps off randomized per-user, per-session hostnames, which effectively prevents XSRF, reflected XSS, and clickjacking.
- We run each app in a secure sandbox (based on Linux namespaces and seccomp on the server side, and Content-Security-Policy on the client side) which prevents the app with interfering with other apps on the server or communicating with the outside world without permission. So, even if one app is compromised, the damage is contained.
- Our underlying security model is based on capability-based security (which has a large body of research behind it).

Here are some blog posts describing some more details (but not everything):
https://blog.sandstorm.io/news/2014-07-24-tinytinyrss-plus-security-discussion.html
https://blog.sandstorm.io/news/2014-08-13-sandbox-security.html

I certainly don't think developers are stupid! Getting security right is hard, and something that requires specialized expertise. I wouldn't declare my own code secure without a third-party security review. Moreover, even though some developers do actually know how to get it right, it's hard for a user to tell which developers understand security (or even which developers are non-malicious) until it's too late. I think everyone stands to benefit from a platform which implements a much higher baseline of security.

> Basically, Sandstorm tries to convince open-source projects to invest time and work for adopting its specific structure and then generates profits by providing open-source projects as a service. And, due to the fact that it's licensed under the Apache License 2.0, Sandstorm could include features within their SaaS service, which are exclusive to them and won't be made open-source, attracting more users to their hosted environment.

The strategy you describe would actually be self-destructive for us. It might gain some users in the short run but would destroy our credibility with the community and drive away developers, which means we'd have fewer users in the long run. So we won't do that. :)

In fact, the main point of the managed hosting service is to make sure the platform is accessible to everyone -- including those that don't know how to (or simply don't want to) maintain their own servers. We don't expect this to be our main revenue generator in the long run -- we expect to generate revenue by selling cluster management tools and support to enterprise customers. If all our personal users end up running independent federated instances on their own private machines, I think that would be _awesome_. But, I just don't think the average person actually wants to maintain their own server, and I don't think they should be excluded because of that.

We aren't trying to profit off the work of open source developers -- quite the opposite, [my main motivation](https://blog.sandstorm.io/news/2014-07-21-open-source-web-apps-require-federated-hosting.html) for starting Sandstorm was to help open source web apps have a way to reach more users. Building a profitable business simply seems like the best way to ensure success in that goal. :) When we build our app store, we'll let open source projects sell their apps on a "pay what you want" basis, and we won't take any profit on those transactions.

Hope this has made things a little clearer...

**Comment by devilx** [comment]
Hey there @kentonv,

thank you for taking time and replying to this issue! I have a few questions regarding your replies:

> I don't think @CoolkcaH is suggesting that Paperwork should require Sandstorm, just support it. That is, the core would remain independent of Sandstorm, but there would be a Sandstorm package built as one option for deployment, which means the user would have more choices, not fewer.

I wasn't able to find out what *"just support it"* would take. Is there a way to simply build/maintain some docker-like configuration, which would make Paperwork (rudimentary) work on top of Sandstorm, without initially using all the features like the authentication mechanism? Because, if that should be the case, I don't have any headaches with supporting Sandstorm right from the beginning. I just did not want us to modify large amounts of (still unstable) Paperwork code, so that we would end up depending on Sandstorm.

> We handle login at the platform level so that apps never handle user credentials -- which means they can't leak those credentials.
> We handle access control at the platform level so that an app can never accidentally grant access to someone who shouldn't have it.

How does Sandstorm integrate into corporate environments, in the matter of authentication?

> We run each app in a secure sandbox (based on Linux namespaces and seccomp on the server side, and Content-Security-Policy on the client side) which prevents the app with interfering with other apps on the server or communicating with the outside world without permission. So, even if one app is compromised, the damage is contained.

Meaning, that Sandstrom will be limited to Linux environments only? Or are you building an abstraction layer which decides whether to use Linux namespaces, BSD jails, Solaris Zones, etc. depending on what platform Sandstorm is being ran on?

Thank you for clarifying your business model to us and going into more detail regarding a few of the topics I mentioned above!

**Comment by kentonv** [comment]
> I wasn't able to find out what "just support it" would take.

I just got a chance to check out the Paperwork demo -- it looks very nice! I think it will fit very nicely into the Sandstorm model and I'd be excited to see it on the platform.

I also just checked our [app porting voting list](https://sandstorm.io/vote) and it looks like among apps we haven't ported yet, Paperwork is number 4! (The voters here are our "app committee" -- 32 people who purchased voting rights during our Indiegogo campaign.)

So, we might end up doing the work for you, but it would be awesome if we could eventually upstream our changes. :)

While technically it would be possible to shove Paperwork into Sandstorm without any code changes -- e.g. still using its own login system and such -- Sandstorm users won't like this very much as they are used to not having to log into individual apps. Also, once users have installed such a version of Paperwork, it might be hard to migrate them to a more-closely-integrated version in the future.

Instead, the way to support Sandstorm (without requiring it) will be to write bracnhes like "if (sandstorm) x(); else y();" -- or, in many cases, "if (!sandstorm) y();", because on Sandstorm you'll mostly just want to skip code that is no longer needed. :)

In particular, the changes we'd want to make are:

* Skip login. Assume you're storing data only for a single user, and assume that anyone who opens the app has full access to that data. Each user will create their own instance anyway, and Sandstorm will enforce that one user can't get access to another's instance without the owner explicitly sharing it with them. If you ever need to know the user's display name, you can get it from the `X-Sandstorm-Username` header. If you ever need to know whether two sessions were the same person, you can compare the `X-Sandstorm-User-Id` headers (but you probably don't need to). Eventually, we will also have a way for you to define permissions that apply to your app (like "read-only" vs. "writable") at which point the `X-Sandstorm-Permissions` header will list the permissions held by the current user, which you'll want to enforce (but you don't need to implement ACLs yourself; Sandstorm will do that).

* Limit an instance to a single notebook. The user can create multiple instances if they want multiple notebooks. This way they can share one of their notebooks (using Sandstorm sharing) without sharing all of them. (At this point you can probably hide the left sidebar and top bar.)

* For your mobile client API, you'll need to use Sandstorm's support for [exporting HTTP APIs](https://github.com/sandstorm-io/sandstorm/wiki/Exporting-HTTP-APIs). The main trick here is that the user will need to create an API key and feed that into the client app, and your client will need to pass that API key to the server in the `Authorization` header in a specific format. The UX here is currently rather cumbersome; this is something we will be working on. I like your QR code trick! Maybe we should do the same thing in Sandstorm.

Other than that, you'll just need to package the app with the appropriate dependencies and startup script; you can use some of the other PHP-based Sandstorm apps as a model here.

> How does Sandstorm integrate into corporate environments, in the matter of authentication?

We plan to build tools to integrate with LDAP, Active Directory, etc. This may be one of those things that is part of our paid enterprise product. In any case, it will be transparent to the app.

> Meaning, that Sandstrom will be limited to Linux environments only? Or are you building an abstraction layer which decides whether to use Linux namespaces, BSD jails, Solaris Zones, etc. depending on what platform Sandstorm is being ran on?

The trouble here is that app packages contain binaries, and those binaries have to be built for a particular kernel and architecture. We don't want developers to have to compile and test on multiple platforms, so we've settled on Linux-amd64 as our target of choice.
