### ISSUE TITLE
Laravel 5 Socialite Extension to login with multiple OAuth accounts and with email/password login!

### ISSUE THREAD

**Issue by jasondavis** [twostairs/paperwork#240]
http://w3layouts.com/preview/?l=/facebook-twitter-google-login-page/The new Laravel 5 release came with a new extension for the Laravel team called Socialite which allows you to very easily do account creation and login using OAuth in a Laravel app using sites like Google, Facebook, Twitter, Github, etc...

I think that if this is implemented that a create user and login functionality should still also exist with email and password like it is now.

Luckily this extension is so ridiculously easy to use that it would be pretty easy to keep current login and then add some OAuth provider logins as well.

To work correctly like StackExchange does, they allow you to create and login with username/password or to login with like 4 different OAuth providers.  

What is nice is it is set up correctly so that you could technically create an account with any of these methods and then login with any of them as well.  You could create account with Twitter and come back later and login with a Google account and it would still link all your logins to the same account as they all look locally in the database for your Email address!

So you can see if you login with any OAuth provider, it will return your account info from that service/site and you then check the DB for an email matching an account.  Same with username/password login.

Just a cool feature that I have always liked but it;s never been this easy to do!

Here is a quick demo for a UI for OpenID,...even though this is OAtuh, it's the same concept for the UI for a login http://openid-selector.googlecode.com/svn/trunk/demo.html
 Also a screenshot image below to show an example login with local account login + OAuth login

What's everyones thoughts on this?  Worth adding or useless?  It would require the app to upgrade Laravel to version 5 which I think is a good thing anyways!

![facebook-twitter-google-login](https://cloud.githubusercontent.com/assets/186818/6201503/3a5f046e-b47c-11e4-9452-ffe2fc4b68e1.jpg)

**Comment by devilx** [comment]
Thanks for suggesting @jasondavis! There's one major with providing OAuth logins: Users would need to create OAuth apps in order to receive an OAuth app id + secret, which then they need to configure within your Laravel config. I'm not sure, whether that's making things easier.

For cloud services like Evernote and others, social logins are pretty fine, since they create their own OAuth apps, configure them within their platform and users can simply pretty a button to register/login. A self-hosted variant like Paperwork would imply a lot more preparation for the user – and what for? Only that he (and maybe a few others, like his family or his colleagues) could login/register by only pressing one button? Not sure, if it's worth the work.

Besides, Paperwork won't upgrade to L5 that soon. See #54.

**Comment by Liongold** [comment]
Maybe this could be a good idea for plugins when they are implemented? (#223)

**Comment by jasondavis** [comment]
understood, could probably scratch this idea then!
