### ISSUE TITLE
Concept: Search

### ISSUE THREAD

**Issue by mrusme** [twostairs/paperwork#39]
Someone needs to think of a good concept for search. Here are some thoughts on that topic:

Should search be implemented right into the MySQL database or should an Elasticsearch (or whatever) be used? This decision would have a huge impact on the overall complexity of Paperwork. Therefor, maybe abstract the implementation allowing the administrator to decide, whether he'd like to stick with the simple MySQL setup or build a full-blown Elasticsearch solution?

Notes metadata has to be written into the search back-end. In addition, the tesseract OCR would need to write its parsing results into the search back-end as well, to allow the user to search for text that is contained in images he uploads.

Where on the back-end should search be implemented? Is it a task that is being triggered from within the API controller code? Or should it be run as a parallel background job through a job-queue?

How should the search API look like? How will it respond to search requests, if the request would take longer than usual to proceed?

**Comment by jasondavis** [comment]
Personally I prefer the basic MySQL search for the reason that I can simply install this on my localhost server or anywhere I have a LAMP stack running and not have to worry about yet another piece of software being installed and configured.  I can't comment on the other stuff mentioned!

**Comment by devilx** [comment]
@jasondavis simplicity indeed is a good point here. I'm not sure though, whether MySQL (or better MariaDB) will allow us to search a big amount of data within an acceptable time. Imagine a company installation of Paperwork with dozens of notes and attachments inside.

Some search expert is needed here, in order to provide us some insights about how things could be done best, while still keeping things simple for the average Joe.

**Comment by mrusme** [comment]
Will be closed in favour of https://github.com/twostairs/paperwork/issues/896
