### ISSUE TITLE
sorting notes?

### ISSUE THREAD

**Issue by HazenBabcock** [twostairs/paperwork#454]
Is there a way to sort the notes in notebook, perhaps by date? Currently my notes appear to be sorted by their UUID(?). If this feature does not exist, I think it would be useful.

**Comment by Liongold** [comment]
Thanks for dedicating some of your time to contributing to Paperwork. This issue has been fixed in #542 and improved in #547, and therefore this issue will be closed. It is now available on the develop branch of our repository. If you encounter any other issues and/or have any feedback about Paperwork, please open a new issue.

Just an additional note, the default sort order was by creation date (earliest first).
