### ISSUE TITLE
Notes sort order

### ISSUE THREAD

**Issue by PHP-Expert** [twostairs/paperwork#474]
It would be great to sort notes with creation date / modify date / alphabetic

**Comment by daeavelwyn** [comment]
I totaly agree !
other post talking about : https://github.com/twostairs/paperwork/issues/454

**Comment by Liongold** [comment]
Thanks for dedicating some of your time to contributing to Paperwork. This issue has been fixed in #542 and improved in #547, and therefore this issue will be closed. It is now available on the develop branch of our repository. If you encounter any other issues and/or have any feedback about Paperwork, please open a new issue.
