### ISSUE TITLE
"Upload document" button is taking up ~20 % of my screen

### ISSUE THREAD

**Issue by bijancn** [twostairs/paperwork#590]
I usually have my browser only on half of my screen and then the "Upload document" button on the right is really annoying because it reduces the possible size of the input box for the CKEditor.

When I make the window really small, at some point the "Upload document" button ends up at the bottom. I think this position makes more sense for any screen size. (Even better would be probably on the line where the save and close buttons are, aligned to the  left and with a fixed size).

The corresponding classes seem to be `col-md-3` and `col-md-9`. I really think the input box should use as much space as  possible, similar to the expand mode of Evernote's webapp. It helps to concentrate on the content.

**Comment by Liongold** [comment]
The upload document button (and section) is now kept to the bottom when width is less than 995px. Thus, this issue will be considered fixed. If you encounter any new issues or have any other feedback, please open a new issue report. Thanks for your feedback.

**Comment by rroux** [comment]
Remy Roux                                                                                                                                                                                                                De: LiongoldEnvoyé: vendredi 27 mai 2016 16:42À: twostairs/paperworkRépondre à: twostairs/paperworkObjet: Re: [twostairs/paperwork] "Upload document" button is taking up ~20 % of my screen (#590)The upload document button (and section) is now kept to the bottom when width is less than 995px. Thus, this issue will be considered fixed. If you encounter any new issues or have any other feedback, please open a new issue report. Thanks for your feedback.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bijancn** [comment]
Thanks! Looks good :+1:
