### ISSUE TITLE
Laravel 4.2 and PHP 7.1 compatibility

### ISSUE THREAD

**Issue by mheppner** [twostairs/paperwork#745]
Laravel 4.2 used MCrypt, which as been [dropped in PHP 7.1](https://secure.php.net/manual/en/migration71.deprecated.php). Laravel 5.1 started using the OpenSSL extension for encryption. I can't find it anywhere in the release notes, but from [this issue](https://github.com/laravel/framework/issues/16884), it looks like Laravel 4.2 is no longer supported.

Is there any effort underway to switch to Laravel 5.x? If not, I can give it a shot.

**Comment by peyoot** [comment]
I try "php artisan migrate" in master successfully. But failed in dev branch.
This could also be the php version support issue? I use PHP 7.0 in my test.

**Comment by mheppner** [comment]
I'm still working on updating to Laravel 5 in my fork, but I haven't pushed anything yet. Officially, I don't think they add support for PHP 7 until 5.1, but most users report it works with 4.2. Not sure what the difference is in the dev branch though.

**Comment by Liongold** [comment]
@peyoot Your issue does not have to do with your problem. 

@mheppner Right now, there's no work on migrating to a new Laravel version. Laravel 4.2 is a little old but supports PHP7. I am not sure, however, on PHP7.1.

**Comment by Liongold** [comment]
Anyway, there's an issue about migrating to Laravel 5 already. Can you please use #54 please? This issue will be closed to avoid having multiple issues on the same topic. Thanks for your interest.

**Comment by Calystod** [comment]
I have the same problem on my installation. My server use PHP 7.1 and I can't do the setup because of an error with mcrypt. The POST response when I submit my configuration send the error:
`{
"error":{
"type":"ErrorException",
"message":"Function mcrypt_get_iv_size() is deprecated",
"file":"\/var\/www\/paperwork\/frontend\/vendor\/laravel\/framework\/src\/Illuminate\/Encryption\/Encrypter.php",
"line":305
}
}`

mcrypt_get_iv_size() is deprecated for PHP 7.1, the solution is to update Laraval to the version 5. Presently, I updated Laravel to the last version but it was a bad idea, some classes used by paperwork have been removed (Illuminate/Support/ClassLoader in particular).

I will stop for now and test with the version 5.1 of Laravel later.

**Comment by Calystod** [comment]
Thanks !

**Comment by labudis** [comment]
What is the solution to this problem?

**Comment by Liongold** [comment]
You can either merge the code found in #821 to disable the errors (at that point Paperwork *should* work with PHP 7.1 but hasn't been tested) or use the laravel5 version developed in #54.

**Comment by jsEveryDay** [comment]
Can we somehow make use of this? for php 7.1
[laravel/legacy-encrypter](https://github.com/laravel/legacy-encrypter)

Can someone confirm the app is stable on PHP 7.0 with errors suppressed? before I downgrade.

**Comment by zartek-io** [comment]
interested in the resolution to this as well.
