### ISSUE TITLE
Feature Request: Strikethrough in text editor

### ISSUE THREAD

**Issue by TheFiZi** [twostairs/paperwork#753]
Example:

Version 2.0 is <strike>not yet available!</strike> now available!

**Comment by harshnormal** [comment]
You can actually do that already in ckeditor, though by default it is disabled. Modify the following file:
`paperwork/frontend/public/ckeditor/config.js`

and replace
`config.removeButtons = 'Cut,Copy,Paste,Undo,Redo,Anchor,Underline,Strike,Subscript,Superscript';`

with:
`config.removeButtons = 'Cut,Copy,Paste,Undo,Redo,Anchor,Underline,Subscript,Superscript';`

As you can see, this one line removes some other features such as underline and super/subscript.

**Comment by TheFiZi** [comment]
Thanks!

Can this be added as a enable/disable toggle in admin section of Paperwork? If not just enabled by default?

**Comment by Liongold** [comment]
This has been implemented in #794. If someone can test it, some help would be much appreciated.

**Comment by jerheij** [comment]
When I try to change config in ckeditor.js nothing seems to happen, even after a reload of httpd & php-fpm.

**Comment by Liongold** [comment]
#794 has been merged to the develop branch. Any changes to remove or 'unremove' buttons from the editor toolbar can now be done through the `paperwork.json` and not the CKEdit config itself. @jerheij Can you test it using the new method? If it does not work, please re-open this issue. 

Thank you all for your feedback and for using Paperwork. I'll close this issue since this should have been fixed. If anyone encounters any issues with this or any other feature, please open a new issue.

**Comment by jerheij** [comment]
I've downloaded the "develop" branch zip and merged it into my apache paperwork folder with rsync but I. I put the following in my paperwork.json:

> {
>     "registration": "true",
>     "forgot_password": false,
>     "showIssueReportingLink": true,
>     "removeEditorButtonsCKEditor": "Cut"
> }

Yet my ckeditor buttons are no different. How do I know for sure I am running the webapp on the develop branch?
