### ISSUE TITLE
How do I get my paperwork server to re-run the configuration wizard?

### ISSUE THREAD

**Issue by mbrownie1** [twostairs/paperwork#788]
Some dependencies were missing (which it alerted me of) the first time I ran the config wizard.  Now I just want to rerun the wizard to make sure everything checks out.  Rhel7.

**Comment by Liongold** [comment]
To re-run the whole setup wizard, you need to

1. Change the contents of paperwork/frontend/app/storage/config/setup to 0
2. Delete database.json in the same folder
3. Delete paperwork.json in the same folder

Please remember to backup your Paperwork database before doing this since the wizard may reinstall your database. 

I'll close the issue since it's a question. Thanks for using Paperwork. If you need any help with anything else, please open a new issue.

**Comment by mbrownie1** [comment]
Perfect, thanks so much for the info!
