### ISSUE TITLE
Installing Paperwork in Arch Linux is failing

### ISSUE THREAD

**Issue by JohnSheepert** [twostairs/paperwork#808]
I installed all packages via 'npm install' (and the other stuff bower and gulp and so on), but the setup page still tells me that I didn't run 'npm install'. So I skipped the setup with the "workaround".
After I added database.json and paperwork.json and inserted 8 in setup (everything in app/storage/config) I could enter index.php. Now there is a strange page:
![screenshot_2017-06-12_03-20-19](https://user-images.githubusercontent.com/6233221/27016292-747f7f90-4f1e-11e7-9766-7e09607a1ff9.png)
I use PHP@7.1.6 and cannot downgrade.
Do you have any ideas?

**Comment by JohnSheepert** [comment]
Ok, I mixed somehow some paths. After I added database.json and paperwork.json and inserted 8 in setup (everything in app/storage/config) I could enter index.php. Now there is a strange page:
![screenshot_2017-06-12_03-20-19](https://user-images.githubusercontent.com/6233221/27016292-747f7f90-4f1e-11e7-9766-7e09607a1ff9.png)
I use PHP@7.1.6 and cannot downgrade.
Do you have any ideas?

**Comment by Liongold** [comment]
Paperwork is built on Laravel 4.2 which does not seem to support and work on PHP 7.1. Since you said you can't downgrade to PHP 7 (which should work), you can try either

1. following the advice given at https://github.com/laravel/framework/issues/16884 to override the error handling by Laravel
2. use a branch of Paperwork built on Laravel 5 - the code for it can be found https://github.com/twostairs/paperwork/tree/feature/laravel5

I hope this helps. I'll consider this a question and close it. If the options I mentioned do not work, please reopen this issue. Thanks for using Paperwork.

**Comment by Liongold** [comment]
If you are willing to @JohnSheepert, you can test the code found in pull request #821. This implements option 1 of the options I mentioned earlier. If you test it, can you report if it works and whether you find anyother problems, please?
