### ISSUE TITLE
Upgrade to PHP 7?

### ISSUE THREAD

**Issue by klud1** [twostairs/paperwork#819]
Hello, everyone.

I'm not a php expert or anything, but i've been reading about php 7 and the improvements it has. 

(*maybe super dumb*) question...can this project be upgraded to php 7?

**Comment by Liongold** [comment]
Paperwork is based on Laravel 4.2. Laravel 4.2 has been upgraded to work with PHP7, thus Paperwork should work with PHP7 as well. Compatibility with PHP 7.1 has not been tested yet but Laravel 4.2 has not been specifically updated to work with it. More information can be found in #808. Thank you for your interest in Paperwork. Feel free to ask more questions or do other contributions. 

I'll close this issue since it is a question. However, if you don't think I answered feel free re-opening this issue.

**Comment by klud1** [comment]
@Liongold thanks for the answer, as you've seen i opened a PR (#820) though i could do some test with php 7 and 7.x as well.

**Comment by Liongold** [comment]
If you can and want to, It would be a great help if you test Paperwork using PHP 7.1. If you do so, could you please use the code proposed in pull request #821. That should remove the errors brought about by the use of Mcrypt.  Those errors should be the main incompatibility between Paperwork and PHP 7.1. 

If you find any issues, please comment in the pull request itself. Thank you.
