### ISSUE TITLE
Is PHP 7.1 supported?

### ISSUE THREAD

**Issue by listairee** [twostairs/paperwork#837]
Ran 2 different installations, one with 7.0 and it worked fine. 7.1 seems to give me an error on Step 4, configuration has not been set correctly. Wondering if anyone else has issue with PHP 7.1?

**Comment by clemlaf** [comment]
I had to use the feature/laravel5 branch to have Paperwork running on Php7.1

**Comment by listairee** [comment]
Thanks. Will it be merged with master?

**Comment by Liongold** [comment]
As far as I know, there are some missing things in the laravel5 version. #821 proposes some code which should make it possible to run Paperwork in PHP 7.1. Feel free to test that. Otherwise, if you use the laravel5 version, feel free to use it and report any issues you have. 

Thank you for using Paperwork.

**Comment by Liongold** [comment]
I'm closing this as a question. Feel free to open a new issue if you any problems and/or questions about Paperwork.
