### ISSUE TITLE
Is the project dormant?

### ISSUE THREAD

**Issue by alexandery** [twostairs/paperwork#851]
Hi guys,

Is the project no longer actively maintained? Doesn't seem to have too much activity, unless you are done with it and there is no reason for further work.

Thanks!

**Comment by Liongold** [comment]
As it is, Paperwork should work and do its job well. Thus, it still can be installed by new users. Unfortunately, progress on new features and fixes is slow but contributions are still welcome.

**Comment by alexandery** [comment]
Thank you for your reply!

**Comment by jsEveryDay** [comment]
Yes it is dormant!
I got excited when I first found it, I even customized it a bit. Now, there might be small fixes here and there but nothing more. I do regret relying on it, it's limited to PHP 5.6 due to the Laravel version it was built with. Now I'm stuck with Php 5.6 while most apps and the best performance is at PHP 7.1, so now im limited because of it, Occupying a whole server since my apps/new apps req Php 7.0 min

**Comment by JamborJan** [comment]
Hey folks,

I'm not sure who knows how it feels to contribute to OSS projects in your spare time. I'm not talking about any tech giants employees who make 100K plus a year and accidentally worked on a project which has been released as open source by management decision. I'm talking about projects like paperwork which are initiate by individuals because of an idea. 

You start with a good feeling of being able to change something and to have an impact. But very quickly a lot of issues and feature requests are created. People seem not to know that this is your free time away from your family and besides your 100% job you do for a living.

Thats why I wanted to say thank you to @Liongold who is investing countless hours to keep the project going. He is fixing bugs, answering issues, merging PRs and so on. 

On the other hand I totally understand when @jsEveryDay is disappointed. There is a way where we all can get on together. There is an open issue https://github.com/twostairs/paperwork/issues/54 where upgrading to a new laravel version is being tested. As you can see there, I'm also one of these guys trying to contribute as much as possible but with long breaks because I have a real life job and a family. If you have the chance to help, do it. Only with more people actively contributing we are able to keep the project alive.

Thank you and have a great day.

**Comment by Liongold** [comment]
@JamborJan Thank you for your additional explanation and kind words. Also thank you for your help. 

@jsEveryDay To use PHP7, there are 2 options. 
1. Use the Paperwork in the master branch (even though not yet supported - it should work - feel free to open issues if it does not). 
2. Use the Laravel 5.1 version that is being developed in #54. 

If anyone can contribute, please feel free to open pull requests as people are doing for docker compatibility. 

Compliments about the great idea should go to @mrusme who created it. If anyone encounters issues, feel free to report them. There are no guarantees regarding reply times but generally issues get a reply one day or another. 

So (I'm not the creator - so may not be the official position), activity in Paperwork is slow but not 100% stopped. Contributions are welcome. As it is, it should work. But new features may be slow to come.

**Comment by mrusme** [comment]
https://github.com/twostairs/paperwork/tree/2

**Comment by Liongold** [comment]
For information clarity's sake, the code referenced in @mrusme's comment is now in the master branch. The old master code (Paperwork v1) has been moved to the `1` branch.

**Comment by mrusme** [comment]
@Liongold thanks, fixed the link
