### ISSUE TITLE
Sign up won't accept my name

### ISSUE THREAD

**Issue by troelskn** [twostairs/paperwork#86]
I'm greeted with the following message upon signup:

```
The lastname may only contain letters and numbers.
```

My last name has a hyphen in it.

**Comment by ponychicken** [comment]
I would suggest removing any constraints on the name fields. See also: http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by devilx** [comment]
@ponychicken thanks, sounds reasonable! Still, I would like to check whether it's possible to make it configurable before, so that every users can set up their Paperwork service the way they need it.

**Comment by bluebear94** [comment]
I have this problem with my first name (which has a space) too.

**Comment by awchauhdry** [comment]
according to the post link by @ponychicken, the only way to achieve this is to remove any validations at all against the names...

**Comment by ponychicken** [comment]
That's what I would suggest, except maybe a check length > 0

**Comment by devilx** [comment]
@joshlemer committed an initial fix to this in #220, I guess. As soon as it will be configurable through app/config/paperwork.php, this can be closed.

**Comment by joshlemer** [comment]
@troelskn @ponychicken @bluebear94 @awchauhdry Just to let you guys know, the new updated master branch will now allow you to customize the characters allowed in user fist/lastnames. In fact, the new default configuration will probably be fine, since it allows letters, spaces, hyphens, and apostrophes. If you'd like to disallow these, or allow numbers or underscores, you can change the values in /paperwork/frontend/app/config/paperwork.php at lines 87-100.

**Comment by joshlemer** [comment]
Also mentioning people who posted duplicates:

@kiall @heywoodwt @th3m4ri0 @RoryOSiochain
