### ISSUE TITLE
Proposal NW native app

### ISSUE THREAD

**Issue by kenrick** [twostairs/paperwork#87]
Hey everyone, this is an awesome product but no everyone knows how to run it. Maybe a NW.js would compile it into a `native app` so less technical people can use it.

Let me know if this is something you guys would be interested in.

**Comment by devilx** [comment]
Hi @kenrick,

I'm not sure how NW.js could get handy in here. Right now, Paperwork consist of a PHP-back-end and a more-or-less 100% AngularJS front-end, which basically just makes use of the already available REST API the back-end provides.

In future, we will hopefully be able to provide native desktop and mobile apps, that make use of the API. The back-end itself will then still need a bit of know how for running it.

Could you go into further detail on your NW idea? How should this help users running Paperwork?

Thank you!

**Comment by kenrick** [comment]
Oh, so the plan is have a hosted service that you connect to from one of the clients using the api?

Well my idea was to run the php server using node, and use the angular app as the front end in a NW.js app.

**Comment by devilx** [comment]
@kenrick ah, I see. Well yes, you can think of Paperwork just like for example a Drupal or a WordPress: You'll need to have some webserver (e.g. nginx/apache), a PHP and a database (e.g. MySQL) in order to run the service + web-ui. In addition to that, you could connect to its API, with some sort of desktop or mobile client.

I don't think it'll be a good thing to run the whole Paperwork service through NW.js on one single machine, as for example all the shared features wouldn't be available then.

**Comment by kenrick** [comment]
Right I realized that this would be more like a hosted service. In thats case you could give deploy to heroku a shot. A one click way for people to host their own.

**Comment by devilx** [comment]
Let's close this, as Heroku is being worked on in #97.
