### ISSUE TITLE
Docker persistence

### ISSUE THREAD

**Issue by Svarto** [twostairs/paperwork#907]
First of all, super impressed with the quality of paperworks - thanks a lot for all the work you do!

I have a quick question on docker persistence, I want to make sure that my notes and uploads are saved even if I migrate my server to new hardware.

Where are the notes and attachments stores?  

I run a mysql database and I can see entries from paperworks in tables such as "notes" and "attachments" but when I look into these tables I see scrambled data (encrypted?).

Would just be good to know so I don't accidentally lose all my notes. thanks!

**Comment by Liongold** [comment]
Which branch are you using?

**Comment by Svarto** [comment]
Branch 1.

I read the readme that the master branch is not ready yet - is it already usable? Then maybe I'll try and move over 😀

**Comment by Liongold** [comment]
@Svarto No, as far as I know it isn't usable. Since you're using Paperwork, then some things are in the database and others not. In fact,

- Notes, Notebooks, Tags, Version History and User accounts are saved in the Database you defined in database.json
- References to attachments (which attachments have been uploaded and to which notes) is saved in the database
- Raw attachment files are saved in the `frontend/app/storage/attachments` folder
- Configuration settings (database, settings such as showIssueReportingLink, etc. ) are saved in `frontend/app/storage/config` folder

**Comment by Svarto** [comment]
Thanks Liongold!
